package io.github.omegau371.trueimpact;

/** Auto-generated from gradle.properties — do NOT edit this file directly. */
public final class TrueImpactVersion {

    public static final String MOD_ID = "${mod_id}";

    /**
     * Compile-time constant derived from gradle.properties {@code mod_version}.
     * Used only for logging/startup; the status command always reads from ModContainer.
     */
    public static final String VERSION = "${mod_version}";

    private TrueImpactVersion() {}
}
