modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="sabletrueimpact"
version="1.5.0-beta.3.1.3"
displayName="Sable True Impact"
logoFile="sabletrueimpact.png"
authors="omegau371"
description='''
Adds impact damage, cumulative cracking, entity impact damage, and structural fracture behavior to Sable physical structures.

This is an unofficial add-on for Sable and is not affiliated with or endorsed by Sable's original author.
'''

[[mixins]]
config="sabletrueimpact.mixins.json"

[[dependencies.sabletrueimpact]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.226,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sabletrueimpact]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.sabletrueimpact]]
    modId="sable"
    type="required"
    versionRange="[1.2.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.sabletrueimpact]]
    modId="distanthorizons"
    type="optional"
    versionRange="[3.0.3-b,)"
    ordering="AFTER"
    side="CLIENT"
