modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="sabletrueimpact.png"
authors="omegau371"
description='''
True Impact adds experimental physics-based collision damage, cumulative cracking, entity impact damage, and structural fracture behavior to Sable physical structures.

This is an unofficial add-on for Sable and is not affiliated with or endorsed by Sable's original author.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sable"
    type="required"
    versionRange="[1.2.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="distanthorizons"
    type="optional"
    versionRange="[3.0.3-b,)"
    ordering="AFTER"
    side="CLIENT"
