package com.example.sabletrueimpact;

import net.neoforged.neoforge.common.ModConfigSpec;

public final class TrueImpactConfig {
    private static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();

    public static final ModConfigSpec.BooleanValue ENABLE_TRUE_IMPACT;
    public static final ModConfigSpec.DoubleValue GLOBAL_STRENGTH_SCALE;
    public static final ModConfigSpec.BooleanValue ENABLE_SOIL_COMPACTION;
    public static final ModConfigSpec.DoubleValue SOIL_COMPACTION_MIN_VELOCITY;
    public static final ModConfigSpec.DoubleValue SOIL_COMPACTION_MAX_VELOCITY;
    public static final ModConfigSpec.DoubleValue MIN_EFFECT_VELOCITY;
    public static final ModConfigSpec.DoubleValue MIN_BREAK_VELOCITY;
    public static final ModConfigSpec.DoubleValue MIN_PROPAGATION_VELOCITY;
    public static final ModConfigSpec.DoubleValue DAMAGE_SCALE;
    public static final ModConfigSpec.DoubleValue IMPACT_VELOCITY_EXPONENT;
    public static final ModConfigSpec.DoubleValue RESTITUTION_DAMAGE_REDUCTION;
    public static final ModConfigSpec.DoubleValue RESTITUTION_BREAK_VELOCITY_MULTIPLIER;
    public static final ModConfigSpec.DoubleValue ELASTIC_SHATTER_VELOCITY;
    public static final ModConfigSpec.BooleanValue ELASTIC_BLOCKS_BREAK_BLOCKS;
    public static final ModConfigSpec.DoubleValue ELASTIC_SUBLEVEL_DETECTION_RANGE;
    public static final ModConfigSpec.IntValue ELASTIC_SUBLEVEL_SCAN_LIMIT;
    public static final ModConfigSpec.BooleanValue PROTECT_NEARBY_SUBLEVEL_IMPACTS;
    public static final ModConfigSpec.DoubleValue BOUNCE_RESPONSE_SCALE;
    public static final ModConfigSpec.DoubleValue BOUNCE_RESPONSE_THRESHOLD;
    public static final ModConfigSpec.DoubleValue REACTION_RESPONSE_SCALE;
    public static final ModConfigSpec.DoubleValue REACTION_YIELD_LIMIT;
    public static final ModConfigSpec.BooleanValue MOVING_STRUCTURES_BREAK_BLOCKS;
    public static final ModConfigSpec.DoubleValue LOW_FRICTION_DAMAGE_REDUCTION;
    public static final ModConfigSpec.DoubleValue FRAGILE_DAMAGE_MULTIPLIER;
    public static final ModConfigSpec.DoubleValue MASS_EXPONENT;
    public static final ModConfigSpec.DoubleValue FALLBACK_IMPACT_MASS;
    public static final ModConfigSpec.DoubleValue MAX_EFFECTIVE_MASS;
    public static final ModConfigSpec.DoubleValue SOFT_BLOCK_STRENGTH_MULTIPLIER;
    public static final ModConfigSpec.DoubleValue HARDNESS_STRENGTH_FACTOR;
    public static final ModConfigSpec.DoubleValue BLAST_STRENGTH_FACTOR;
    public static final ModConfigSpec.DoubleValue BASE_STRENGTH;
    public static final ModConfigSpec.DoubleValue CRACK_YIELD_THRESHOLD;
    public static final ModConfigSpec.DoubleValue BREAK_YIELD_THRESHOLD;
    public static final ModConfigSpec.DoubleValue HEAVY_BREAK_YIELD_THRESHOLD;
    public static final ModConfigSpec.DoubleValue PROPAGATION_YIELD_THRESHOLD;
    public static final ModConfigSpec.BooleanValue ENABLE_CRACKS;
    public static final ModConfigSpec.BooleanValue ENABLE_BLOCK_BREAKING;
    public static final ModConfigSpec.BooleanValue ENABLE_CRACK_PROPAGATION;
    public static final ModConfigSpec.IntValue MAX_PROPAGATION_BLOCKS;
    public static final ModConfigSpec.DoubleValue PROPAGATION_MIN_ENERGY;
    public static final ModConfigSpec.DoubleValue PROPAGATION_ENERGY_SCALE;
    public static final ModConfigSpec.DoubleValue SAME_BLOCK_DECAY;
    public static final ModConfigSpec.DoubleValue DIFFERENT_BLOCK_DECAY;
    public static final ModConfigSpec.DoubleValue PROPAGATION_CRACK_YIELD_THRESHOLD;
    public static final ModConfigSpec.BooleanValue ENABLE_PAIR_REACTION;
    public static final ModConfigSpec.DoubleValue PAIR_REACTION_SCALE;
    public static final ModConfigSpec.DoubleValue PAIR_REACTION_MAX_IMPULSE;
    public static final ModConfigSpec.DoubleValue PAIR_REACTION_MAX_VELOCITY_CHANGE;
    public static final ModConfigSpec.DoubleValue PAIR_REACTION_FORCE_THRESHOLD;
    public static final ModConfigSpec.BooleanValue ENABLE_TERRAIN_IMPACT_DAMAGE;
    public static final ModConfigSpec.DoubleValue TERRAIN_IMPACT_DAMAGE_SCALE;
    public static final ModConfigSpec.DoubleValue TERRAIN_IMPACT_FORCE_THRESHOLD;
    public static final ModConfigSpec.DoubleValue TERRAIN_IMPACT_FORCE_EXPONENT;
    public static final ModConfigSpec.DoubleValue TERRAIN_IMPACT_MASS_EXPONENT;
    public static final ModConfigSpec.DoubleValue TERRAIN_IMPACT_MAX_EFFECTIVE_MASS;
    public static final ModConfigSpec.DoubleValue TERRAIN_STEP_CONTACT_FORGIVENESS;
    public static final ModConfigSpec.DoubleValue TERRAIN_STEP_SIDE_NORMAL_THRESHOLD;
    public static final ModConfigSpec.DoubleValue TERRAIN_IMPACT_BREAK_YIELD;
    public static final ModConfigSpec.IntValue TERRAIN_IMPACT_MAX_BLOCKS;
    public static final ModConfigSpec.BooleanValue ENABLE_ENTITY_IMPACT_DAMAGE;
    public static final ModConfigSpec.DoubleValue ENTITY_IMPACT_DAMAGE_SCALE;
    public static final ModConfigSpec.DoubleValue ENTITY_IMPACT_MIN_DAMAGE;
    public static final ModConfigSpec.DoubleValue ENTITY_IMPACT_MAX_DAMAGE;
    public static final ModConfigSpec.DoubleValue ENTITY_IMPACT_RADIUS;
    public static final ModConfigSpec.DoubleValue ENTITY_MOVING_IMPACT_DAMAGE_SCALE;
    public static final ModConfigSpec.DoubleValue ENTITY_MOVING_IMPACT_MAX_DAMAGE;
    public static final ModConfigSpec.DoubleValue ENTITY_MOVING_IMPACT_CONTACT_MARGIN;
    public static final ModConfigSpec.DoubleValue ENTITY_MOVING_IMPACT_MIN_RELATIVE_SPEED;
    public static final ModConfigSpec.DoubleValue ENTITY_MOVING_IMPACT_MIN_CLOSING_SPEED;
    public static final ModConfigSpec.DoubleValue ENTITY_STANDING_SUPPORT_TOLERANCE;
    public static final ModConfigSpec.DoubleValue ENTITY_STANDING_MAX_UPWARD_SPEED;
    public static final ModConfigSpec.DoubleValue ENTITY_IMPACT_MIN_SPEED;
    public static final ModConfigSpec.IntValue ENTITY_IMPACT_COOLDOWN_TICKS;
    public static final ModConfigSpec.IntValue ENTITY_IMPACT_SCAN_INTERVAL_TICKS;
    public static final ModConfigSpec.IntValue ENTITY_IMPACT_MAX_SUBLEVELS_PER_SCAN;
    public static final ModConfigSpec.BooleanValue ENABLE_SUBLEVEL_FRACTURE;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_FORCE_THRESHOLD;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_FORCE_SCALE;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_FORCE_EXPONENT;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_RADIUS;
    public static final ModConfigSpec.IntValue SUBLEVEL_FRACTURE_MAX_BLOCKS;
    public static final ModConfigSpec.IntValue SUBLEVEL_FRACTURE_MAX_CANDIDATE_CHECKS;
    public static final ModConfigSpec.IntValue SUBLEVEL_FRACTURE_MAX_CANDIDATES;
    public static final ModConfigSpec.IntValue SUBLEVEL_FRACTURE_COOLDOWN_TICKS;
    public static final ModConfigSpec.IntValue SUBLEVEL_FRACTURE_MAX_ATTEMPTS_PER_TICK;
    public static final ModConfigSpec.IntValue SUBLEVEL_FRACTURE_SNAPSHOT_PADDING;
    public static final ModConfigSpec.BooleanValue ENABLE_ASYNC_FRACTURE_ANALYSIS;
    public static final ModConfigSpec.IntValue ASYNC_FRACTURE_MAX_QUEUED_JOBS;
    public static final ModConfigSpec.IntValue ASYNC_FRACTURE_MAX_APPLIED_JOBS_PER_TICK;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_FRICTION_RESISTANCE;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_SAME_BLOCK_RESISTANCE;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_STICKY_RESISTANCE;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_MASS_REFERENCE;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_MASS_BONUS_SCALE;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_IMBALANCE_BONUS_SCALE;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_IMBALANCE_MAX_MULTIPLIER;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_CHANCE_SCALE;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_IMPACT_FOCUS_EXPONENT;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_CRACK_BONUS_SCALE;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_FATIGUE_SCALE;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_INTERLOCK_STRENGTH;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_BEAM_STRENGTH;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_CONTINUOUS_SEAM_WEAKNESS;
    public static final ModConfigSpec.DoubleValue SUBLEVEL_FRACTURE_WEAK_PLANE_SPREAD;
    public static final ModConfigSpec.BooleanValue ENABLE_EXPLOSION_IMPACT_FRACTURE;
    public static final ModConfigSpec.DoubleValue EXPLOSION_IMPACT_FORCE_SCALE;
    public static final ModConfigSpec.DoubleValue EXPLOSION_IMPACT_RADIUS_MULTIPLIER;
    public static final ModConfigSpec.DoubleValue EXPLOSION_IMPACT_CONFINEMENT_SCALE;
    public static final ModConfigSpec.IntValue EXPLOSION_IMPACT_MAX_SUBLEVELS;
    public static final ModConfigSpec.IntValue EXPLOSION_IMPACT_RAY_SAMPLES;
    public static final ModConfigSpec.DoubleValue EXPLOSION_IMPACT_RAY_STEP;
    public static final ModConfigSpec.BooleanValue ENABLE_EXPLOSION_IMPULSE;
    public static final ModConfigSpec.DoubleValue EXPLOSION_IMPULSE_SCALE;
    public static final ModConfigSpec.DoubleValue EXPLOSION_MAX_IMPULSE;
    public static final ModConfigSpec.BooleanValue ENABLE_IMPACT_EXPLOSIONS;
    public static final ModConfigSpec.DoubleValue IMPACT_EXPLOSION_FORCE_THRESHOLD;
    public static final ModConfigSpec.DoubleValue IMPACT_EXPLOSION_MASS_THRESHOLD;
    public static final ModConfigSpec.DoubleValue IMPACT_EXPLOSION_SCALE;
    public static final ModConfigSpec.DoubleValue IMPACT_EXPLOSION_MAX_RADIUS;
    public static final ModConfigSpec.DoubleValue IMPACT_EXPLOSION_FIRE_CHANCE;
    public static final ModConfigSpec.IntValue IMPACT_EXPLOSION_MAX_PER_BATCH;
    public static final ModConfigSpec.DoubleValue IMPACT_EXPLOSION_COALESCE_RADIUS;
    public static final ModConfigSpec.BooleanValue ENABLE_MATERIAL_TOUGHNESS;
    public static final ModConfigSpec.DoubleValue DEFAULT_MATERIAL_STRENGTH_MULTIPLIER;
    public static final ModConfigSpec.DoubleValue DEFAULT_MATERIAL_TOUGHNESS_MULTIPLIER;
    public static final ModConfigSpec.DoubleValue DEFAULT_MATERIAL_BRITTLENESS;
    public static final ModConfigSpec.DoubleValue NETHERITE_STRENGTH_MULTIPLIER;
    public static final ModConfigSpec.DoubleValue NETHERITE_TOUGHNESS_MULTIPLIER;
    public static final ModConfigSpec.DoubleValue NETHERITE_BRITTLENESS;
    public static final ModConfigSpec.BooleanValue ENABLE_GOGGLES_BLOCK_TOOLTIP;
    public static final ModConfigSpec.BooleanValue ENABLE_CUMULATIVE_BLOCK_DAMAGE;
    public static final ModConfigSpec.DoubleValue CUMULATIVE_BLOCK_DAMAGE_SCALE;
    public static final ModConfigSpec.IntValue CUMULATIVE_BLOCK_DAMAGE_DECAY_TICKS;
    public static final ModConfigSpec.IntValue CUMULATIVE_BLOCK_DAMAGE_MAX_ENTRIES;
    public static final ModConfigSpec.BooleanValue ENABLE_PERFORMANCE_LOGGING;
    public static final ModConfigSpec.IntValue PERFORMANCE_LOG_INTERVAL_TICKS;
    
    // Distant Horizons Proxy Configs
    public static final ModConfigSpec.BooleanValue ENABLE_DH_SUBLEVEL_PROXY_LOD;
    public static final ModConfigSpec.DoubleValue DH_SUBLEVEL_PROXY_MIN_DISTANCE;
    public static final ModConfigSpec.DoubleValue DH_SUBLEVEL_PROXY_MAX_DISTANCE;

    public static final ModConfigSpec SPEC;

    static {
        BUILDER.push("general");
        ENABLE_TRUE_IMPACT = BUILDER.define("enableTrueImpact", true);
        GLOBAL_STRENGTH_SCALE = BUILDER.defineInRange("globalStrengthScale", 1.0, 0.0, 1000.0);
        DAMAGE_SCALE = BUILDER.defineInRange("damageScale", 1.0, 0.0, 1000.0);
        BUILDER.pop();

        BUILDER.push("compaction");
        ENABLE_SOIL_COMPACTION = BUILDER.define("enableSoilCompaction", true);
        SOIL_COMPACTION_MIN_VELOCITY = BUILDER.defineInRange("soilCompactionMinVelocity", 4.0, 0.0, 1000.0);
        SOIL_COMPACTION_MAX_VELOCITY = BUILDER.defineInRange("soilCompactionMaxVelocity", 16.0, 0.0, 1000.0);
        BUILDER.pop();

        BUILDER.push("thresholds");
        MIN_EFFECT_VELOCITY = BUILDER.defineInRange("minEffectVelocity", 2.0, 0.0, 1000.0);
        MIN_BREAK_VELOCITY = BUILDER.defineInRange("minBreakVelocity", 4.5, 0.0, 1000.0);
        MIN_PROPAGATION_VELOCITY = BUILDER.defineInRange("minPropagationVelocity", 8.0, 0.0, 1000.0);
        IMPACT_VELOCITY_EXPONENT = BUILDER.defineInRange("impactVelocityExponent", 1.2, 0.1, 10.0);
        BUILDER.pop();

        BUILDER.push("elasticity");
        RESTITUTION_DAMAGE_REDUCTION = BUILDER.defineInRange("restitutionDamageReduction", 0.85, 0.0, 1.0);
        RESTITUTION_BREAK_VELOCITY_MULTIPLIER = BUILDER.defineInRange("restitutionBreakVelocityMultiplier", 1.4, 1.0, 10.0);
        ELASTIC_SHATTER_VELOCITY = BUILDER.defineInRange("elasticShatterVelocity", 14.0, 0.0, 1000.0);
        ELASTIC_BLOCKS_BREAK_BLOCKS = BUILDER.define("elasticBlocksBreakBlocks", false);
        ELASTIC_SUBLEVEL_DETECTION_RANGE = BUILDER.defineInRange("elasticSubLevelDetectionRange", 4.0, 0.0, 32.0);
        ELASTIC_SUBLEVEL_SCAN_LIMIT = BUILDER.defineInRange("elasticSubLevelScanLimit", 128, 1, 10000);
        PROTECT_NEARBY_SUBLEVEL_IMPACTS = BUILDER.define("protectNearbySubLevelImpacts", true);
        BOUNCE_RESPONSE_SCALE = BUILDER.defineInRange("bounceResponseScale", 0.65, 0.0, 10.0);
        BOUNCE_RESPONSE_THRESHOLD = BUILDER.defineInRange("bounceResponseThreshold", 0.45, 0.0, 1.0);
        REACTION_RESPONSE_SCALE = BUILDER.defineInRange("reactionResponseScale", 0.45, 0.0, 10.0);
        REACTION_YIELD_LIMIT = BUILDER.defineInRange("reactionYieldLimit", 0.85, 0.0, 1.0);
        BUILDER.pop();

        BUILDER.push("structural");
        MOVING_STRUCTURES_BREAK_BLOCKS = BUILDER.define("movingStructuresBreakBlocks", true);
        LOW_FRICTION_DAMAGE_REDUCTION = BUILDER.defineInRange("lowFrictionDamageReduction", 0.6, 0.0, 1.0);
        FRAGILE_DAMAGE_MULTIPLIER = BUILDER.defineInRange("fragileDamageMultiplier", 2.2, 1.0, 10.0);
        MASS_EXPONENT = BUILDER.defineInRange("massExponent", 0.85, 0.0, 2.0);
        FALLBACK_IMPACT_MASS = BUILDER.defineInRange("fallbackImpactMass", 1.0, 0.01, 100000.0);
        MAX_EFFECTIVE_MASS = BUILDER.defineInRange("maxEffectiveMass", 100.0, 1.0, 100000.0);
        SOFT_BLOCK_STRENGTH_MULTIPLIER = BUILDER.defineInRange("softBlockStrengthMultiplier", 1.0, 1.0, 1000.0);
        HARDNESS_STRENGTH_FACTOR = BUILDER.defineInRange("hardnessStrengthFactor", 20.0, 0.0, 1000.0);
        BLAST_STRENGTH_FACTOR = BUILDER.defineInRange("blastStrengthFactor", 18.0, 0.0, 1000.0);
        BASE_STRENGTH = BUILDER.defineInRange("baseStrength", 12.0, 0.0, 1000.0);
        CRACK_YIELD_THRESHOLD = BUILDER.defineInRange("crackYieldThreshold", 1.15, 0.0, 1000.0);
        BREAK_YIELD_THRESHOLD = BUILDER.defineInRange("breakYieldThreshold", 9.5, 0.0, 1000.0);
        HEAVY_BREAK_YIELD_THRESHOLD = BUILDER.defineInRange("heavyBreakYieldThreshold", 16.0, 0.0, 1000.0);
        PROPAGATION_YIELD_THRESHOLD = BUILDER.defineInRange("propagationYieldThreshold", 22.0, 0.0, 1000.0);
        ENABLE_CRACKS = BUILDER.define("enableCracks", true);
        ENABLE_BLOCK_BREAKING = BUILDER.define("enableBlockBreaking", true);
        ENABLE_CRACK_PROPAGATION = BUILDER.define("enableCrackPropagation", true);
        BUILDER.pop();

        BUILDER.push("propagation");
        MAX_PROPAGATION_BLOCKS = BUILDER.defineInRange("maxPropagationBlocks", 24, 0, 10000);
        PROPAGATION_MIN_ENERGY = BUILDER.defineInRange("propagationMinEnergy", 42.0, 0.0, 1000000.0);
        PROPAGATION_ENERGY_SCALE = BUILDER.defineInRange("propagationEnergyScale", 0.026, 0.0, 1000.0);
        SAME_BLOCK_DECAY = BUILDER.defineInRange("sameBlockDecay", 0.45, 0.0, 1.0);
        DIFFERENT_BLOCK_DECAY = BUILDER.defineInRange("differentBlockDecay", 0.20, 0.0, 1.0);
        PROPAGATION_CRACK_YIELD_THRESHOLD = BUILDER.defineInRange("propagationCrackYieldThreshold", 0.75, 0.0, 1000.0);
        BUILDER.pop();

        BUILDER.push("pairReaction");
        ENABLE_PAIR_REACTION = BUILDER.define("enablePairReaction", true);
        PAIR_REACTION_SCALE = BUILDER.defineInRange("pairReactionScale", 0.025, 0.0, 10.0);
        PAIR_REACTION_MAX_IMPULSE = BUILDER.defineInRange("pairReactionMaxImpulse", 250.0, 0.0, 1000000.0);
        PAIR_REACTION_MAX_VELOCITY_CHANGE = BUILDER.defineInRange("pairReactionMaxVelocityChange", 3.0, 0.0, 1000.0);
        PAIR_REACTION_FORCE_THRESHOLD = BUILDER.defineInRange("pairReactionForceThreshold", 50.0, 0.0, 1000000.0);
        BUILDER.pop();

        BUILDER.push("terrainImpact");
        ENABLE_TERRAIN_IMPACT_DAMAGE = BUILDER.define("enableTerrainImpactDamage", true);
        TERRAIN_IMPACT_DAMAGE_SCALE = BUILDER.defineInRange("terrainImpactDamageScale", 0.00016, 0.0, 1000.0);
        TERRAIN_IMPACT_FORCE_THRESHOLD = BUILDER.defineInRange("terrainImpactForceThreshold", 2200.0, 0.0, 1000000000.0);
        TERRAIN_IMPACT_FORCE_EXPONENT = BUILDER.defineInRange("terrainImpactForceExponent", 1.0, 0.0, 8.0);
        TERRAIN_IMPACT_MASS_EXPONENT = BUILDER.defineInRange("terrainImpactMassExponent", 0.7, 0.0, 2.0);
        TERRAIN_IMPACT_MAX_EFFECTIVE_MASS = BUILDER.defineInRange("terrainImpactMaxEffectiveMass", 35.0, 1.0, 100000.0);
        TERRAIN_STEP_CONTACT_FORGIVENESS = BUILDER.defineInRange("terrainStepContactForgiveness", 0.22, 0.0, 1.0);
        TERRAIN_STEP_SIDE_NORMAL_THRESHOLD = BUILDER.defineInRange("terrainStepSideNormalThreshold", 0.35, 0.0, 1.0);
        TERRAIN_IMPACT_BREAK_YIELD = BUILDER.defineInRange("terrainImpactBreakYield", 8.5, 0.0, 1000.0);
        TERRAIN_IMPACT_MAX_BLOCKS = BUILDER.defineInRange("terrainImpactMaxBlocks", 4, 0, 10000);
        BUILDER.pop();

        BUILDER.push("entityImpact");
        ENABLE_ENTITY_IMPACT_DAMAGE = BUILDER.define("enableEntityImpactDamage", true);
        ENTITY_IMPACT_DAMAGE_SCALE = BUILDER.defineInRange("entityImpactDamageScale", 0.18, 0.0, 1000.0);
        ENTITY_IMPACT_MIN_DAMAGE = BUILDER.defineInRange("entityImpactMinDamage", 1.0, 0.0, 1000.0);
        ENTITY_IMPACT_MAX_DAMAGE = BUILDER.defineInRange("entityImpactMaxDamage", 18.0, 0.0, 1000000.0);
        ENTITY_IMPACT_RADIUS = BUILDER.defineInRange("entityImpactRadius", 1.75, 0.0, 32.0);
        ENTITY_MOVING_IMPACT_DAMAGE_SCALE = BUILDER.defineInRange("entityMovingImpactDamageScale", 0.006, 0.0, 1000.0);
        ENTITY_MOVING_IMPACT_MAX_DAMAGE = BUILDER.defineInRange("entityMovingImpactMaxDamage", 6.0, 0.0, 1000000.0);
        ENTITY_MOVING_IMPACT_CONTACT_MARGIN = BUILDER.defineInRange("entityMovingImpactContactMargin", 0.18, 0.0, 4.0);
        ENTITY_MOVING_IMPACT_MIN_RELATIVE_SPEED = BUILDER.defineInRange("entityMovingImpactMinRelativeSpeed", 3.0, 0.0, 1000.0);
        ENTITY_MOVING_IMPACT_MIN_CLOSING_SPEED = BUILDER.defineInRange("entityMovingImpactMinClosingSpeed", 1.75, 0.0, 1000.0);
        ENTITY_STANDING_SUPPORT_TOLERANCE = BUILDER.defineInRange("entityStandingSupportTolerance", 0.35, 0.0, 4.0);
        ENTITY_STANDING_MAX_UPWARD_SPEED = BUILDER.defineInRange("entityStandingMaxUpwardSpeed", 1.25, 0.0, 1000.0);
        ENTITY_IMPACT_MIN_SPEED = BUILDER.defineInRange("entityImpactMinSpeed", 4.0, 0.0, 1000.0);
        ENTITY_IMPACT_COOLDOWN_TICKS = BUILDER.defineInRange("entityImpactCooldownTicks", 20, 0, 200);
        ENTITY_IMPACT_SCAN_INTERVAL_TICKS = BUILDER.defineInRange("entityImpactScanIntervalTicks", 2, 1, 200);
        ENTITY_IMPACT_MAX_SUBLEVELS_PER_SCAN = BUILDER.defineInRange("entityImpactMaxSubLevelsPerScan", 96, 1, 1000000);
        BUILDER.pop();

        BUILDER.push("subLevelFracture");
        ENABLE_SUBLEVEL_FRACTURE = BUILDER.define("enableSubLevelFracture", true);
        SUBLEVEL_FRACTURE_FORCE_THRESHOLD = BUILDER.defineInRange("subLevelFractureForceThreshold", 850.0, 0.0, 1000000000.0);
        SUBLEVEL_FRACTURE_FORCE_SCALE = BUILDER.defineInRange("subLevelFractureForceScale", 0.068, 0.0, 1000.0);
        SUBLEVEL_FRACTURE_FORCE_EXPONENT = BUILDER.defineInRange("subLevelFractureForceExponent", 1.0, 0.0, 8.0);
        SUBLEVEL_FRACTURE_RADIUS = BUILDER.defineInRange("subLevelFractureRadius", 4.0, 0.0, 32.0);
        SUBLEVEL_FRACTURE_MAX_BLOCKS = BUILDER.defineInRange("subLevelFractureMaxBlocks", 18, 0, 10000);
        SUBLEVEL_FRACTURE_MAX_CANDIDATE_CHECKS = BUILDER.defineInRange("subLevelFractureMaxCandidateChecks", 384, 1, 1000000);
        SUBLEVEL_FRACTURE_MAX_CANDIDATES = BUILDER.defineInRange("subLevelFractureMaxCandidates", 96, 1, 1000000);
        SUBLEVEL_FRACTURE_COOLDOWN_TICKS = BUILDER.defineInRange("subLevelFractureCooldownTicks", 4, 0, 200);
        SUBLEVEL_FRACTURE_MAX_ATTEMPTS_PER_TICK = BUILDER.defineInRange("subLevelFractureMaxAttemptsPerTick", 8, 1, 1000000);
        SUBLEVEL_FRACTURE_SNAPSHOT_PADDING = BUILDER.defineInRange("subLevelFractureSnapshotPadding", 1, 0, 4);
        ENABLE_ASYNC_FRACTURE_ANALYSIS = BUILDER.define("enableAsyncFractureAnalysis", false);
        ASYNC_FRACTURE_MAX_QUEUED_JOBS = BUILDER.defineInRange("asyncFractureMaxQueuedJobs", 64, 1, 1000000);
        ASYNC_FRACTURE_MAX_APPLIED_JOBS_PER_TICK = BUILDER.defineInRange("asyncFractureMaxAppliedJobsPerTick", 4, 1, 10000);
        SUBLEVEL_FRACTURE_FRICTION_RESISTANCE = BUILDER.defineInRange("subLevelFractureFrictionResistance", 1.6, 0.0, 1000.0);
        SUBLEVEL_FRACTURE_SAME_BLOCK_RESISTANCE = BUILDER.defineInRange("subLevelFractureSameBlockResistance", 1.6, 0.0, 1000.0);
        SUBLEVEL_FRACTURE_STICKY_RESISTANCE = BUILDER.defineInRange("subLevelFractureStickyResistance", 10000.0, 1.0, 1000000000.0);
        SUBLEVEL_FRACTURE_MASS_REFERENCE = BUILDER.defineInRange("subLevelFractureMassReference", 14.0, 1.0, 1000000.0);
        SUBLEVEL_FRACTURE_MASS_BONUS_SCALE = BUILDER.defineInRange("subLevelFractureMassBonusScale", 0.8, 0.0, 1000.0);
        SUBLEVEL_FRACTURE_IMBALANCE_BONUS_SCALE = BUILDER.defineInRange("subLevelFractureImbalanceBonusScale", 0.85, 0.0, 1000.0);
        SUBLEVEL_FRACTURE_IMBALANCE_MAX_MULTIPLIER = BUILDER.defineInRange("subLevelFractureImbalanceMaxMultiplier", 4.0, 1.0, 1000.0);
        SUBLEVEL_FRACTURE_CHANCE_SCALE = BUILDER.defineInRange("subLevelFractureChanceScale", 1.25, 0.0, 1000.0);
        SUBLEVEL_FRACTURE_IMPACT_FOCUS_EXPONENT = BUILDER.defineInRange("subLevelFractureImpactFocusExponent", 1.8, 0.1, 10.0);
        SUBLEVEL_FRACTURE_CRACK_BONUS_SCALE = BUILDER.defineInRange("subLevelFractureCrackBonusScale", 3.0, 0.0, 1000.0);
        SUBLEVEL_FRACTURE_FATIGUE_SCALE = BUILDER.defineInRange("subLevelFractureFatigueScale", 0.22, 0.0, 1000.0);
        SUBLEVEL_FRACTURE_INTERLOCK_STRENGTH = BUILDER.defineInRange("subLevelFractureInterlockStrength", 1.8, 0.0, 1000.0);
        SUBLEVEL_FRACTURE_BEAM_STRENGTH = BUILDER.defineInRange("subLevelFractureBeamStrength", 2.4, 0.0, 1000.0);
        SUBLEVEL_FRACTURE_CONTINUOUS_SEAM_WEAKNESS = BUILDER.defineInRange("subLevelFractureContinuousSeamWeakness", 1.7, 0.0, 1000.0);
        SUBLEVEL_FRACTURE_WEAK_PLANE_SPREAD = BUILDER.defineInRange("subLevelFractureWeakPlaneSpread", 0.55, 0.0, 1000.0);
        BUILDER.pop();

        BUILDER.push("explosionImpact");
        ENABLE_EXPLOSION_IMPACT_FRACTURE = BUILDER.define("enableExplosionImpactFracture", true);
        EXPLOSION_IMPACT_FORCE_SCALE = BUILDER.defineInRange("explosionImpactForceScale", 950.0, 0.0, 1000000.0);
        EXPLOSION_IMPACT_RADIUS_MULTIPLIER = BUILDER.defineInRange("explosionImpactRadiusMultiplier", 1.85, 0.0, 32.0);
        EXPLOSION_IMPACT_CONFINEMENT_SCALE = BUILDER.defineInRange("explosionImpactConfinementScale", 6.5, 0.0, 100.0);
        EXPLOSION_IMPACT_MAX_SUBLEVELS = BUILDER.defineInRange("explosionImpactMaxSubLevels", 32, 1, 1000000);
        EXPLOSION_IMPACT_RAY_SAMPLES = BUILDER.defineInRange("explosionImpactRaySamples", 48, 6, 512);
        EXPLOSION_IMPACT_RAY_STEP = BUILDER.defineInRange("explosionImpactRayStep", 0.75, 0.1, 4.0);
        ENABLE_EXPLOSION_IMPULSE = BUILDER.define("enableExplosionImpulse", true);
        EXPLOSION_IMPULSE_SCALE = BUILDER.defineInRange("explosionImpulseScale", 0.018, 0.0, 1000.0);
        EXPLOSION_MAX_IMPULSE = BUILDER.defineInRange("explosionMaxImpulse", 80.0, 0.0, 1000000.0);
        BUILDER.pop();

        BUILDER.push("impactExplosion");
        ENABLE_IMPACT_EXPLOSIONS = BUILDER.define("enableImpactExplosions", false);
        IMPACT_EXPLOSION_FORCE_THRESHOLD = BUILDER.defineInRange("impactExplosionForceThreshold", 5000.0, 0.0, 1000000000.0);
        IMPACT_EXPLOSION_MASS_THRESHOLD = BUILDER.defineInRange("impactExplosionMassThreshold", 15.0, 0.0, 1000000.0);
        IMPACT_EXPLOSION_SCALE = BUILDER.defineInRange("impactExplosionScale", 0.000018, 0.0, 100.0);
        IMPACT_EXPLOSION_MAX_RADIUS = BUILDER.defineInRange("impactExplosionMaxRadius", 12.0, 0.0, 64.0);
        IMPACT_EXPLOSION_FIRE_CHANCE = BUILDER.defineInRange("impactExplosionFireChance", 0.0, 0.0, 1.0);
        IMPACT_EXPLOSION_MAX_PER_BATCH = BUILDER.defineInRange("impactExplosionMaxPerBatch", 1, 1, 64);
        IMPACT_EXPLOSION_COALESCE_RADIUS = BUILDER.defineInRange("impactExplosionCoalesceRadius", 16.0, 0.0, 256.0);
        BUILDER.pop();

        BUILDER.push("materialToughness");
        ENABLE_MATERIAL_TOUGHNESS = BUILDER.define("enableMaterialToughness", true);
        DEFAULT_MATERIAL_STRENGTH_MULTIPLIER = BUILDER.defineInRange("defaultMaterialStrengthMultiplier", 1.0, 0.0, 1000000.0);
        DEFAULT_MATERIAL_TOUGHNESS_MULTIPLIER = BUILDER.defineInRange("defaultMaterialToughnessMultiplier", 1.0, 0.0, 1000000.0);
        DEFAULT_MATERIAL_BRITTLENESS = BUILDER.defineInRange("defaultMaterialBrittleness", 1.0, 0.0, 1000000.0);
        NETHERITE_STRENGTH_MULTIPLIER = BUILDER.defineInRange("netheriteStrengthMultiplier", 14.0, 0.0, 1000000.0);
        NETHERITE_TOUGHNESS_MULTIPLIER = BUILDER.defineInRange("netheriteToughnessMultiplier", 48.0, 0.0, 1000000.0);
        NETHERITE_BRITTLENESS = BUILDER.defineInRange("netheriteBrittleness", 0.018, 0.0, 1000000.0);
        BUILDER.pop();

        BUILDER.push("client");
        ENABLE_GOGGLES_BLOCK_TOOLTIP = BUILDER.define("enableGogglesBlockTooltip", true);
        BUILDER.pop();

        BUILDER.push("cumulativeDamage");
        ENABLE_CUMULATIVE_BLOCK_DAMAGE = BUILDER.define("enableCumulativeBlockDamage", true);
        CUMULATIVE_BLOCK_DAMAGE_SCALE = BUILDER.defineInRange("cumulativeBlockDamageScale", 0.65, 0.0, 1000.0);
        CUMULATIVE_BLOCK_DAMAGE_DECAY_TICKS = BUILDER.defineInRange("cumulativeBlockDamageDecayTicks", 600, 20, 72000);
        CUMULATIVE_BLOCK_DAMAGE_MAX_ENTRIES = BUILDER.defineInRange("cumulativeBlockDamageMaxEntries", 4096, 128, 1000000);
        BUILDER.pop();

        BUILDER.push("performance");
        ENABLE_PERFORMANCE_LOGGING = BUILDER.define("enablePerformanceLogging", false);
        PERFORMANCE_LOG_INTERVAL_TICKS = BUILDER.defineInRange("performanceLogIntervalTicks", 200, 20, 72000);
        BUILDER.pop();
        
        BUILDER.push("distantHorizons");
        ENABLE_DH_SUBLEVEL_PROXY_LOD = BUILDER.comment("Experimental: render Sable sublevels as Distant Horizons LODs for massive fleets.")
                .define("enableDHSubLevelProxyLod", false);
        DH_SUBLEVEL_PROXY_MIN_DISTANCE = BUILDER.comment("Minimum distance to start rendering DH proxies (should be near your chunk render distance).")
                .defineInRange("dhSubLevelProxyMinDistance", 256.0, 0.0, 10000.0);
        DH_SUBLEVEL_PROXY_MAX_DISTANCE = BUILDER.comment("Maximum distance to render DH proxies.")
                .defineInRange("dhSubLevelProxyMaxDistance", 2048.0, 0.0, 10000.0);
        BUILDER.pop();

        SPEC = BUILDER.build();
    }

    private TrueImpactConfig() {
    }
}
